# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dev-terraform-state28072022"
    dynamodb_table = "dev-terraform-state28072022"
    encrypt        = true
    key            = "dev/pipelines/terraform.tfstate"
    region         = "eu-west-2"
  }
}
